In [1]:
import torch
print(torch.__version__)

import numpy as np

2.14.0


# 1.Tensor的理解：
    1.常数，scaler:0阶张量
    2.向量, vector,1阶张量
    3.矩阵, matrix:2阶张量
    4.3阶张量
# 2. 创建张量的方法：
     1.使用列表创建Tensor
     2.使用numpy数组创建Tensor
     3.通过torch的API创建Tensor
     
# 3. 张量的方法和属性
    1.tensor.item(),当tensor中只有一个元素可以用的时候
    2.Tensor转为ndarray
    3.形状修改，tensor.view((3, 4)), 类似numpy中的reshape,是一种浅拷贝
    4.获取维数、转置、轴滚动。
    5.在方法后加_，会原地修改，相当于Tensorflow里的inplace

# 2. 创建张量的方法

In [3]:
# 1. 使用列表创建Tensor
t1 = torch.Tensor([1, 2, 3])
print(t1)
"""
tensor([1., 2., 3])
"""

# 2. 使用numpy数组创建Tensor
array1 = np.arange(12).reshape(3, 4)

t2 = torch.Tensor(array1)
print(t2)

tensor([1., 2., 3.])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [4]:
# 3. 通过torch的API创建Tensor
"""
torch.empty(3, 4)：创建3行4列的空的tensor，会用无用的数据进行填充
torch.ones([3, 4])：3行4列全为1的tensor
torch.zeros([3, 4])：3行4列全为0的tensor
torch.rand([3, 4])：3行4列随机值在[0, 1]之间的值
torch.randint(low = 0, high = 10, size = [3, 4]) 创建3 * 4的随机整数Tensor，值区间：[low, high]
torch.randn([3, 4])均值为0，方差为1，3*4 的tensor
"""
print(torch.empty(3, 4))
print(torch.ones([3, 4]))
print(torch.zeros([3, 4]))
# 每个元素从[0, 1)的均匀分布里随机采样(包含0，不包含1)
print(torch.rand([3, 4]))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.0210, 0.7347, 0.7919, 0.5392],
        [0.9648, 0.4864, 0.7820, 0.7376],
        [0.9159, 0.5775, 0.8001, 0.1909]])


In [5]:
# 每个元素从[0, 10)里随机取（包含0，不包含10），也就是取值只能是 0～9
print(torch.randint(low = 0, high = 10, size = [3, 4]))
"""
标准化 != 正态化，但正态化一定是标准化
randn = random + normal
    由于正态分布曲线与x轴面积的问题，68%的数值落在 (-1, 1) 之间
"""
print(torch.randn([3, 4]))

tensor([[9, 7, 8, 1],
        [8, 2, 3, 9],
        [7, 4, 3, 7]])
tensor([[ 0.0314,  1.4623, -0.1067,  0.9300],
        [-0.3773,  1.6201, -0.7430,  0.3008],
        [-2.0118,  0.7366, -0.6079, -1.5410]])


# 3. 张量的方法和属性

In [9]:
# 1. tensor.item()，当tensor中只有一个元素可以用的时候
a = torch.tensor(np.arange(1))
print(a)
# 只有一个元素的时候可以用，返回一个python的标量，不可以用于多个元素的tensor
print(a.item())
print('--' * 50)
# .item()只要求张量里元素总数为1，跟它的形状/维度无关；也就是必须只有一个元素，而不是“必须是0维”
print(torch.Tensor([[[1]]]).item())

tensor([0])
0
----------------------------------------------------------------------------------------------------
1.0


In [12]:
# 2. Tensor转为ndarray
t2 = torch.Tensor([3, 4])
print(t2.numpy())

print(t2.shape)
print(t2.size())
print(t2.size(0))

[3. 4.]
torch.Size([2])
torch.Size([2])
2


In [13]:
# 2. Tensor转为ndarray
"""
t2 = torch.Tensor([[3, 4]]) -> 创建一个 1*2 的张量：
    用torch.Tensor（大写T）默认是float32，所以3、4变成 3. 、4.
t2.numpy() -> 把张量转成 Numpy 数组：
    前提：张量在CPU上且requires_grad=False，否则会报错
t2.shape:
    第0维大小 = 1（1行）
    第1维大小 = 2（2列）
t2.size():
    size()不传参时，等价于shape
    注：shape是属性，size()是方法，结果一样
t2.size(1):
    返回第1维（从0开始数）的大小
    t2.size(0) -> 1
    t2.size(1) -> 2
"""
t2 = torch.Tensor([[3, 4]])
print(t2.numpy())
# 两种获取形状的方式
print(t2.shape)
print(t2.size())
# 返回第一维的大小
print(t2.size(1))

[[3. 4.]]
torch.Size([1, 2])
torch.Size([1, 2])
2


In [14]:
t2

tensor([[3., 4.]])

In [15]:
# 写一个ndarray
"""
为什么id不同但内存相同
    id()            Python对象标识，不同对象就不同，array1和array2是两个不同的Python对象
    底层数据         可以多个对象共享同一块内存，reshape通常不复制数据
    reshape创建了一个新的ndarray对象（新的shape、新的strides），但它指向原数组的数据缓冲区
如果无法用“改变视图”的方式完成reshape（比如内存不连续），NumPy会复制：
    array1 = np.array([[1, 2, 3], [4, 5, 6]])
    array2 = array1.T.reshape(3, 2)   # 转置后不连续，可能复制
    print(np.shares_memory(array1, array2))   # 可能 False
        此时array2和array1完全独立
"""
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(id(array1))
array2 = array1.reshape(3, 2)
print(id(array2))

4500867856
4499597872


In [16]:
# 此时修改array2时，array1也会同时改变
array2[0, 0] = 100
print(array1)
print(array2)

[[100   2   3]
 [  4   5   6]]
[[100   2]
 [  3   4]
 [  5   6]]


In [17]:
print(array1.ndim)
print(array2.ndim)

2
2


In [18]:
# 3. 形状修改，tensor.view((3, 4))，类似numpy中的reshape，是一种浅拷贝，仅仅形状发生改变，返回一个新的结果
t2 = torch.Tensor([[[3, 4]]])
print(t2.size())                                    # 三维张量
print(t2.view([1, 2]))                              # 二维张量（1行2列）
print(t2.view([2]))                                 # 一维张量（2列）
b = t2.view([2, -1])                                # -1表示自动计算
print(b)
print('--' * 50)
print(t2)                                           # t2的形状并没有发生改变
# https://pytorch.org/docs/stable/tensor_view.html
t2.storage().untyped().data_ptr() == b.storage().untyped().data_ptr()   # 判断两个tensor是否共享内存

torch.Size([1, 1, 2])
tensor([[3., 4.]])
tensor([3., 4.])
tensor([[3.],
        [4.]])
----------------------------------------------------------------------------------------------------
tensor([[[3., 4.]]])


/var/folders/pb/p_cly9gj3xv6l7083h32ln_80000gn/T/ipykernel_69014/1485371350.py:11: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  t2.storage().untyped().data_ptr() == b.storage().untyped().data_ptr()


True

In [19]:
b[0, 0] = 100
print(b)
print(t2)

tensor([[100.],
        [  4.]])
tensor([[[100.,   4.]]])


In [22]:
print(t2.dim())                         # 获取维数

print(t2.max())                         # 获取最大值

t3 = torch.tensor([[1, 3, 4], [2, 4, 6]])
print(t3)
print(t3.t())                           # 转置

3
tensor(100.)
tensor([[1, 3, 4],
        [2, 4, 6]])
tensor([[1, 2],
        [3, 4],
        [4, 6]])


In [23]:
print(id(t3))
print(id(t3.t()))

4509872320
4509864640


In [ ]:
t4 = torch.tensor(np.arange(24).reshape(2, 3, 4))
print(t4.shape)
print('--' * 50)
print(t4.transpose(0, 1).shape)                             # 交换0轴和1轴